### ISSUE TITLE
error when running python2 ./from_mxnet.py

### ISSUE THREAD

**Issue by kaishijeng** [liangfu/mxnet-mobilenet-v2#1]
Any idea why clip is not supported in nnvm belo. My nnvm is the latest one.

TVM: Initializing cython mode...
/home/firefly/2TB/src/firefly/incubator-mxnet-04-13/python/mxnet/__init__.pyc
/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/__init__.pyc
/usr/local/lib/python2.7/dist-packages/tvm-0.2.0-py2.7-linux-aarch64.egg/tvm/__init__.pyc
('x', (1, 3, 224, 224))
Traceback (most recent call last):
  File "./from_mxnet.py", line 82, in <module>
    nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 354, in from_mxnet
    sym = _from_mxnet_impl(symbol, {})
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 317, in _from_mxnet_impl
    childs = [_from_mxnet_impl(childs[i], graph) for i in range(len(childs.list_outputs()))]
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 319, in _from_mxnet_impl
    node = _convert_symbol(op_name, childs, attr)
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 278, in _convert_symbol
    _raise_not_supported('Operator: ' + op_name)
  File "/home/firefly/2TB/src/firefly/nnvm-04-12/python/nnvm/frontend/mxnet.py", line 24, in _raise_not_supported
    raise NotImplementedError(err)
NotImplementedError: Operator: clip is not supported in nnvm.

Thanks,

**Comment by liangfu** [comment]
I'm glad you would try the inference code, however, it requires an PR submission [here](https://github.com/dmlc/nnvm/pull/435) . For a quick solution, you can simply add `'clip'`to the `_identity_list` variable in `frontend/mxnet.py` .
